import type { Fighter } from "./types"

/*
 * ============================================================
 * FIGHT SIMULATION SYSTEM
 * ============================================================
 *
 * Responsible for simulating what happens when two fighters
 * actually fight.
 *
 * V1 is intentionally simple.
 *
 * This system does NOT handle:
 *
 * - matchmaking
 * - event scheduling
 * - contracts
 * - injuries
 * - rivalries
 * - rankings
 * - championship history
 *
 * Those systems remain separate.
 */

/*
 * ============================================================
 * FIGHT RESULT
 * ============================================================
 */

export type FightMethod =
  | "KO"
  | "TKO"
  | "Submission"
  | "Decision"

export type FightResult = {
  fighterAId: string
  fighterBId: string

  winnerId: string

  method: FightMethod

  round: number

  time: number
}

/*
 * ============================================================
 * FIGHT SIMULATION
 * ============================================================
 *
 * Simulates one fight between two fighters.
 *
 * V1 uses the fighter attributes already generated by
 * fighterGenerator.ts.
 *
 * The simulation is intentionally lightweight.
 */

export function simulateFight(
  fighterA: Fighter,
  fighterB: Fighter
): FightResult {
  /*
   * ----------------------------------------------------------
   * Calculate overall combat strengths
   * ----------------------------------------------------------
   */

  const fighterAStrength =
    fighterA.striking +
    fighterA.wrestling +
    fighterA.bjj +
    fighterA.accuracy +
    fighterA.power +
    fighterA.speed +
    fighterA.cardio +
    fighterA.chin +
    fighterA.strength +
    fighterA.fightIQ +
    fighterA.heart

  const fighterBStrength =
    fighterB.striking +
    fighterB.wrestling +
    fighterB.bjj +
    fighterB.accuracy +
    fighterB.power +
    fighterB.speed +
    fighterB.cardio +
    fighterB.chin +
    fighterB.strength +
    fighterB.fightIQ +
    fighterB.heart

  /*
   * ----------------------------------------------------------
   * Add randomness
   * ----------------------------------------------------------
   *
   * A stronger fighter should generally win more often,
   * but MMA should never be completely predictable.
   */

  const randomA =
    Math.random() * 100

  const randomB =
    Math.random() * 100

  const finalA =
    fighterAStrength + randomA

  const finalB =
    fighterBStrength + randomB

  const winner =
    finalA >= finalB
      ? fighterA
      : fighterB

  const loser =
    winner.id === fighterA.id
      ? fighterB
      : fighterA

  /*
   * ----------------------------------------------------------
   * Determine fight method
   * ----------------------------------------------------------
   *
   * V1 uses the winner's offensive attributes and the loser's
   * defensive attributes to influence the result.
   */

  const finishingPower =
    winner.power +
    winner.striking +
    winner.bjj +
    winner.accuracy

  const resistance =
    loser.chin +
    loser.takedownDefense +
    loser.heart

  const finishChance =
    finishingPower - resistance

  const finishRoll =
    Math.random() * 100

  /*
   * ----------------------------------------------------------
   * KO / TKO
   * ----------------------------------------------------------
   */

  if (
    finishChance > 80 &&
    finishRoll < 35
  ) {
    return {
      fighterAId: fighterA.id,
      fighterBId: fighterB.id,
      winnerId: winner.id,
      method:
        finishRoll < 18
          ? "KO"
          : "TKO",
      round:
        Math.floor(
          Math.random() * 4
        ) + 1,
      time:
        Math.floor(
          Math.random() * 300
        ) + 1,
    }
  }

  /*
   * ----------------------------------------------------------
   * Submission
   * ----------------------------------------------------------
   */

  const submissionAbility =
    winner.bjj +
    winner.wrestling

  const submissionResistance =
    loser.bjj +
    loser.wrestling +
    loser.takedownDefense

  const submissionChance =
    submissionAbility -
    submissionResistance

  const submissionRoll =
    Math.random() * 100

  if (
    submissionChance > 20 &&
    submissionRoll < 20
  ) {
    return {
      fighterAId: fighterA.id,
      fighterBId: fighterB.id,
      winnerId: winner.id,
      method: "Submission",
      round:
        Math.floor(
          Math.random() * 4
        ) + 1,
      time:
        Math.floor(
          Math.random() * 300
        ) + 1,
    }
  }

  /*
   * ----------------------------------------------------------
   * Decision
   * ----------------------------------------------------------
   *
   * If nobody finishes the fight, it goes to the judges.
   */

  return {
    fighterAId: fighterA.id,
    fighterBId: fighterB.id,
    winnerId: winner.id,
    method: "Decision",
    round: 3,
    time: 300,
  }
}